### PR TITLE
Added minetweaker integreating

### PR DESCRIPTION
**Pull request by AEnterprise**
added integration for the calculators and the machines.
test script: https://gist.github.com/AEnterprise/b209f9bd2432286eaf79

redid the conductor mast recipes to make this possible, also oredict entries are stored as part of the recipe instead of the stacks that can be used, this means the validation against the oredict is done at the moment the recipe is determined so if a mod heapens to only add something to the oredict at an extremely late state that is no longer an issue, nei handlers are updated to compensate for it

for the removal of recipes see the pr in the core repo, also made some tweaks to other things i encountered along the way

### CODE REVIEW

**Comment by SonarSonic** [comment]
Awesome work!!!!! Thanks so much for this AEnterprise. I'll test out and release a new version :)

**Comment by AEnterprise** [comment]
no problem, recipe removal is still a bit derpy when reloading instead of re-launching, was unable to figure out the exact cause but other then that it should all work fine

**Comment by SonarSonic** [comment]
It'll mostly be mod packs devs changing recipes though so people playing the pack wouldn't get any derp right?

**Comment by AEnterprise** [comment]
in the pack it will be alright for the end users as they shouldn't be /mt reload, as far as i can see the problem lies the fact that if the recipe get's added again with the undo it doesn't match anymore when it tries to remove it again, spent quite some time on the why but was unable to find an exact cause

i won't have time to look furter intro this over the next days so i did the pr anyways so you don't have to wait

also i noticed i derped: look at the diff, i did a refactor and intelliJ renamed some comments, "recipe" => "recipeOutput", sorry!

**Comment by SonarSonic** [comment]
I might have a look into it tonight when I test. Haha that's fine I'll sort out little things like that

**Comment by AEnterprise** [comment]
alright, you have a much better understanding of the recipe code, though a little suggestion: eighter put them all in the registry class our of it, some are internal classes, some are not

also maybe get rid of the temp lists where you store recipes before adding them, add them directly to the right lists, no point in first storing them somewhere else in my opinion ;)

**Comment by AEnterprise** [comment]
final note: things will not work or print an error in the MT log (but will in the forge log) if someone passes a fluidstack instead of an iitemstack or oredict entry but did that to prevent the huge number of combinations i would have to make functions with for MT as entry points, the flawless calc would have needed 32 otherwise iirc

also feel free to pass me any bug reports that come from this if needed

**Pull request merged**
