### PR TITLE
Trying to fix #97 and #84

### LINKED ISSUE #97: 2 minor bugs with Progressive Automation and 1 major with 1.9.9 version of the mod
1) End forged pick/shovel aren't accepted into PA miner (diamond tier; electric ones are accepted though, didn't test axe and chopper). I think it's related to #84 and setting durability to for example int_max - 1 should fix this. Can't test though.
2) ?! When PA is installed Calculator Wrench is called PA wrench instead:

3) How is Calc Flux Point crafted? I found only impossible recipe (divide fire block by ender-pearl in Scientific Calculator, but I don't know ways to gather Fire Blocks).
Edit: MAJOR 1.9.9 issue. The Flux Point, Advanced Terrain Module and Redstone Extractor use oreDict entry ingotRedstone in crafting (https://github.com/SonarSonic/Calculator/blob/master/src/main/java/sonar/calculator/mod/common/recipes/RecipeRegistry.java, lines 548, 559, 567) but you deleted that entry in 1.9.9 update to prevent #95. Redstone tools _can_ be crafted. Please fix...

### PR DESCRIPTION
**Pull request by MineWitherMC**
Can't test though as Calc isn't compiling for me.

### CODE REVIEW

**Comment by SonarSonic** [comment]
That would make End Forged Tools Breakable. Also i'm pretty sure we shouldn't have to change the unlocalized name of the wrench as the lang files should be localized to Calculator only. That PA Wrench error could be someone in another mod using the system wrong. The Redstone Ingot changes make sense.

**Comment by MineWitherMC** [comment]
@SonarSonic I'm sure that setting EFT durab to 2^31-2 will allow them to be used in PA machines & BC robots while not losing status of tools with (almost) infinite durab (over 2 billion) (however, I can delete that commit if you need that).
I don't know what creates issue with PA wrench (pretty sure it's minecraft engine or forge issue), the only thing I found is that that wrench is called item.Wrench.name the same as calc wrench.
Sorry for crappy english (if it is).

**Comment by SonarSonic** [comment]
Yes it would make them work but I should be able to find another work around.
Yeah the PA wrench is a strange one, I'm not sure about it at the moment.

**Comment by AEnterprise** [comment]
localizations files are not mod specific at all, they are all merged into one (per language) at runtime, this is why most mods have there modname/id/... as prefix in the lang keys, to prevent these kinds conflicts

**Comment by AEnterprise** [comment]
@MineWitherMC how are you sure that setting the durability that high will allow them to work as you said you can't compile? i suspect that progressive automation is checking for some vanilla class/interface that the calc tools don't implement

**Comment by SonarSonic** [comment]
@AEnterprise  I didn't know that. Seems a bit stupid :P I don't want to go and change all the names now though and have ID conflicts. But i'll change them for 1.8.9 Versions

**Comment by AEnterprise** [comment]
you can change the names no problem, there's a setUnlocalizedName(...) function you can call on your items/blocks

**Comment by MineWitherMC** [comment]
@AEnterprise I tried electric diamond tools and it worked...

**Comment by AEnterprise** [comment]
yes, i'm not @SonarSonic so sorry if i'm out of line here but i make a big difference between "it should work but i didn't test" and "it works because i tested it"

also on the 'merging' of lang files: minecraft originally wasn't made (and technically still isn't) to natively support mods, localizations work with a hashmap or something similar and in the end all entries end up in the same one, no prefixing done as that can only break things and cause confustion

**Comment by SonarSonic** [comment]
@AEnterprise no it's fair enough. I had never looked into this myself. I assume many things :P

**Comment by SonarSonic** [comment]
I found other ways to fix most of these. Haven't fixed Wrench Glitch yet. Do you think you could do commits in separate pull requests in future. Thanks for all your help :)

**Pull request closed without merging**
