### PR TITLE
Fixes duplicate blockstate files in git.

### PR DESCRIPTION
**Pull request by pupnewfster**
This should make pulling the branch not throw errors about the files already existing.

### CODE REVIEW

**Comment by AEnterprise** [comment]
this PR introduces 30,000 new lines are you sure everything went right with this PR? github can't preview all files

**Comment by pupnewfster** [comment]
Ya, it is just that my IDE ended up formatting the json files, I can fix that later I suppose. I was just going to be lazy but actually there is a decent way I can do it.

**Comment by pupnewfster** [comment]
That didn't seem to work properly, so I will fix it some time later today, or recreate the pull request if for somereason it is an issue with git not recognizing the change. Because git is not counting the line changes for the most recent commit correctly.

**Comment by AEnterprise** [comment]
if it's just that then i think it'll be fine, was just asking cause usually when you get 30k extra lines someone commited his logs or compiler output folder

**Comment by pupnewfster** [comment]
Then I will leave it, especially now that I fixed it so that formatting isn't all different (from what I can tell) and git is just claiming that the commit doing that barely changed any lines.

**Comment by pupnewfster** [comment]
There, I managed to fix it so that the formatting isn't changed, and it doesn't claim there are soo many files. I had missed a folder earlier except for introducing the spacing changes. I will also fix all the spacing changes I did by accident in the Sonar Core pull.

**Comment by AEnterprise** [comment]
thanks, makes this PR alot easier to look at

**Pull request merged**
